export const UPDATE_ACTIVE_SECTION = 'app/charts/UPDATE_ACTIVE_SECTION'
export const UPDATE_BLOCKCHAIN_STATS = 'app/charts/UPDATE_BLOCKCHAIN_STATS'
export const UPDATE_CHART_NAME = 'app/charts/UPDATE_CHART_NAME'
export const UPDATE_ACTIVE_DATA_CARD = 'app/charts/UPDATE_ACTIVE_DATA_CARD'
export const LOAD_STATS = 'app/charts/FETCH_STATS'
export const LOAD_STATS_SUCCESS = 'app/charts/FETCH_STATS_SUCCESS'
export const LOAD_STATS_ERROR = 'app/charts/FETCH_STATS_ERROR'
